packages:
  - '**'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  cypress: true
  esbuild: true
  prisma: true
  sharp: true
ignoredBuiltDependencies:
  - cypress
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - sharp
